import Head from 'next/head'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { getAuth } from 'firebase/auth';

import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import SignInButtom from '../../components/signIn'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}> Login</h1>
        <SignInButtom />
      </main>
    </>
  )
}
